### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Dobbelsteen**
Updated the site to oSoc2015 with new style.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Are the right files compressed and ready here? The FAQ doesn't expand

**Comment by Dobbelsteen** [comment]
FAQ expands on my end in every browser I try. 
It only doesn't work if JavaScript is disabled. (which was the default in my IE for some reason)
I updated the PDF in the latest development version

**Comment by pietercolpaert** [comment]
Can you try a fresh checkout? I think some files are not included in your
commit...

Op zo 19 apr. 2015 12:59 schreef Sander Meert notifications@github.com:

**Comment by Dobbelsteen** [comment]
It's probably because I put the bower_components folder in the .gitignore file.
I'll change it so that folder also gets pushed

**Comment by pietercolpaert** [comment]
Or maybe just include build instructions? Bad idea to include bower components in a git repo

**Comment by Dobbelsteen** [comment]
Sorry, completely forgot about any documentation. I reverted the changes and added deployment instructions to the readme.
Are these sufficient? The mentioned steps are the only ones I have to take in my environment. Or should I mention the use of Node Packet Manager as well.

**Comment by Dobbelsteen** [comment]
A few unnoticed bugs were discovered today, I fixed them all (that I know of)
Hopefully no more will arise

**Pull request merged**
